package matrix_test

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/nabrahma/lathe/internal/deps"
	"github.com/nabrahma/lathe/internal/engine"
	"github.com/nabrahma/lathe/internal/engine/ffmpegengine"
	"github.com/nabrahma/lathe/internal/pipeline"
	"github.com/nabrahma/lathe/internal/task"
)

// Media tests need FFmpeg, which is a downloaded component rather than a
// bundled one. They skip when it is absent so a contributor without it still
// gets a green run; CI and the Docker test image both have it.
//
// The sample clip is generated by FFmpeg itself rather than committed, which
// keeps a multi-megabyte binary out of the repository.

func TestMediaTasks(t *testing.T) {
	manager, err := deps.New(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	if !manager.Available("ffmpeg") {
		t.Skip("FFmpeg is not installed on this machine")
	}

	clip := makeClip(t, manager)
	registry := task.Default()
	runner := pipeline.New(engine.NewRegistry(ffmpegengine.New(manager)), nil)

	cases := []struct {
		name    string
		taskID  string
		options map[string]any
	}{
		{"convert to mp4", "media.convert-video", map[string]any{"format": "mp4", "quality": "low"}},
		{"compress with a height limit", "media.compress-video",
			map[string]any{"format": "mp4", "quality": "low", "maxHeight": "240"}},
		{"extract audio as mp3", "media.extract-audio", map[string]any{"format": "mp3"}},
		{"extract audio as wav", "media.extract-audio", map[string]any{"format": "wav"}},
		{"convert audio", "media.convert-audio", map[string]any{"format": "m4a"}},
		{"video to gif", "media.video-to-gif",
			map[string]any{"start": "0", "duration": 1, "width": "320"}},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			tk, ok := registry.Get(tc.taskID)
			if !ok {
				t.Fatalf("no such task %q", tc.taskID)
			}

			before := hashAll(t, []string{clip})
			outDir := t.TempDir()

			opts := engine.Options(tk.Defaults())
			for k, v := range tc.options {
				opts[k] = v
			}

			res, err := runner.Run(context.Background(), pipeline.Request{
				Task: tk, Inputs: []string{clip}, Options: opts, OutputDir: outDir,
			})
			if err != nil {
				t.Fatalf("%v", err)
			}
			if after := hashAll(t, []string{clip}); after != before {
				t.Fatal("the input clip was modified")
			}
			if len(res.Outputs) != 1 {
				t.Fatalf("got %d outputs, want 1", len(res.Outputs))
			}
			if info, err := os.Stat(res.Outputs[0]); err != nil || info.Size() < 256 {
				t.Fatalf("output is missing or implausibly small: %v", err)
			}
		})
	}
}

func TestMediaProgressIsReal(t *testing.T) {
	manager, err := deps.New(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	if !manager.Available("ffmpeg") {
		t.Skip("FFmpeg is not installed on this machine")
	}

	clip := makeClip(t, manager)
	tk, _ := task.Default().Get("media.convert-video")
	runner := pipeline.New(engine.NewRegistry(ffmpegengine.New(manager)), nil)

	var sawRealFraction bool
	opts := engine.Options(tk.Defaults())
	opts["quality"] = "low"

	_, err = runner.Run(context.Background(), pipeline.Request{
		Task: tk, Inputs: []string{clip}, Options: opts, OutputDir: t.TempDir(),
		Progress: func(p engine.Progress) {
			// FFmpeg reports elapsed output time, so a real fraction should
			// appear rather than only the indeterminate -1.
			if p.Fraction > 0 && p.Fraction <= 1 {
				sawRealFraction = true
			}
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	if !sawRealFraction {
		t.Error("no real progress fraction was reported; the bar would be indeterminate for no reason")
	}
}

// makeClip renders a short test video with FFmpeg's own sources.
func makeClip(t *testing.T, manager deps.Manager) string {
	t.Helper()

	bin, err := manager.BinaryPath("ffmpeg", "ffmpeg")
	if err != nil {
		t.Skipf("FFmpeg not found: %v", err)
	}

	clip := filepath.Join(t.TempDir(), "clip.mp4")
	cmd := exec.Command(bin, //nolint:gosec // test fixture, path comes from the component manager
		"-hide_banner", "-loglevel", "error", "-y",
		"-f", "lavfi", "-i", "testsrc=size=320x240:rate=15:duration=3",
		"-f", "lavfi", "-i", "sine=frequency=440:duration=3",
		"-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest",
		clip)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Skipf("could not build a test clip: %v\n%s", err, out)
	}
	return clip
}
