/*
 * Extracts the task icons from pixelarticons into a committed source file.
 *
 * The package stays a dev dependency: the bundle is embedded in the binary and
 * ships offline, so the handful of glyphs actually used are baked in rather
 * than pulled at runtime. Re-run with "npm run gen:icons" after changing the
 * map below.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const svgDir = join(here, "..", "node_modules", "pixelarticons", "svg");
const out = join(here, "..", "src", "components", "pixelGlyphs.ts");

// Lathe's task icon names on the left, the pixelarticons file on the right.
const map = {
  compress: "collapse",
  merge: "git-merge",
  split: "git-branch",
  rotate: "redo",
  delete: "trash",
  reorder: "sort-vertical",
  watermark: "brush",
  lock: "lock",
  unlock: "unlock",
  images: "images",
  pdf: "file-text",
  convert: "arrows-horizontal",
  resize: "scale",
  crop: "crop",
  text: "text-start-t",
  search: "search",
  document: "article",
  word: "text-align-left",
  video: "video",
  audio: "music",
  gif: "repeat",
};

function pathsOf(name) {
  const svg = readFileSync(join(svgDir, `${name}.svg`), "utf8");
  const found = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
  if (found.length === 0) throw new Error(`no path data in ${name}.svg`);
  return found;
}

const entries = Object.entries(map)
  .map(([key, file]) => {
    const d = pathsOf(file)
      .map((p) => `    ${JSON.stringify(p)},`)
      .join("\n");
    return `  // ${file}\n  ${key}: [\n${d}\n  ],`;
  })
  .join("\n");

writeFileSync(
  out,
  `/*
 * Generated by scripts/gen-icons.mjs. Do not edit by hand.
 *
 * Task icons from pixelarticons (MIT), drawn on a 24 by 24 pixel grid. See
 * docs/LICENSES.md for the notice.
 */

export const GLYPH_SIZE = 24;

export const glyphs: Record<string, string[]> = {
${entries}
};
`,
  "utf8",
);

console.log(`wrote ${Object.keys(map).length} glyphs to ${out}`);
